# Generated by Django 5.1.1 on 2024-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(choices=[('Mr.', 'Mr'), ('Ms.', 'Ms'), ('Mx.', 'Mx'), ('Mrs.', 'Mrs'), ('Miss', 'Mis'), ('Dr.', 'Dr'), ('Sir', 'Sr'), ('Dame', 'Dm'), ('Lord', 'Ld'), ('Lady', 'Ly')], default=None, max_length=4)),
                ('age', models.IntegerField(default=0)),
                ('hometown', models.CharField(max_length=200)),
            ],
        ),
    ]
