# Generated by Django 5.1.1 on 2024-09-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0002_alter_personal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
