# Generated by Django 5.1.1 on 2024-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0003_alter_personal_age_alter_personal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='title',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('', '')], max_length=50),
        ),
    ]
