# Generated by Django 5.1.1 on 2024-09-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission_form', '0004_alter_personal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personal',
            name='hometown',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
